version: '3.7'
services:
  web:
    image: pizzafox/maroon
    build:
      context: '.' 
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "80:30"
    environment:
      - YOUTUBE_API_KEY=12445
      - SQREEN_TOKEN=5d6e84d710cf1fd
      - PORT=80
    networks:
      - webnet
networks:
  webnet:
